Web_backend/Models/Director.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_backend.Models
{
    public class Director
    {
            public List<List_Director> director { get; set; } 
    }
    public class List_Director
    {
        public string ID_Directer { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
    }
}

Web_backend/Controllers/AddController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_backend.Models;

namespace Web_backend.Controllers
{
    public class AddController : Controller
    {

        private string APIURL = string.Empty;
        // GET: Add
        public ActionResult Movie(Add.Input_movie Input, HttpPostedFileBase file)
        {
            var guid = Session["Guid"] as string;
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.img = returnedClass.Image(file,Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }
            
            Input.ID_User = new Guid(guid);

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Movie", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Movie");
        }
        public ActionResult Caster(Add.Input_caster Input, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.PictureUrl = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }


            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Caster", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Caster");
        }
        public ActionResult Caster_M(Add.Input_caster Input, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.PictureUrl = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }


            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Caster", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Add", "Movie");
        }
        public ActionResult Director(Add.Input_director Input, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.PictureUrl = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }


            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Director", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Director");
        }
        public ActionResult Director_M(Add.Input_director Input, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.PictureUrl = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }


            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Director", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Add", "Movie");
        }
        public ActionResult Genre(Add.Input_Genre Input)
        {

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Genre", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Genre");
        }
        public ActionResult Studio(Add.Input_Studio Input)
        {

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/Studio", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Studio");
        }
        public ActionResult News(Add.Input_News Input)
        {

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Add/News", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "News");
        }
    }
}

Web_backend/Controllers/DeleteController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Web_backend.Models.Delete;

namespace Web_backend.Controllers
{
    public class DeleteController : Controller
    {
        private string APIURL = string.Empty;
        // GET: Delete
        public ActionResult Director(Input_Director input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/Director", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Director");
        }
        public ActionResult Movie(Input_Movie input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/Movie", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Movie");
        }
        public ActionResult Caster(Input_Caster input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/Caster", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Caster");
        }
        public ActionResult Genre(Input_Genre input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/Genre", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Genre");
        }
        public ActionResult Studio(Input_Studio input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/Studio", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Studio");
        }
        public ActionResult User(Input_User input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/User", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Users");
        }
        public ActionResult News(Input_News input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Delete/News", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "News");
        }
        public ActionResult Comment(Input_Comment input)
        {
            Output output_ = new Output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Review/Delete_Comment", input);
            output_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Output>(result);

            return RedirectToAction("Index", "Comment");
        }
    }

}

Web_backend/Controllers/DirectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Web_backend.Helper;
using Web_backend.Models;

namespace Web_backend.Controllers
{
    public class DirectorController : Controller
    {
        // GET: Directer
        public ActionResult Index()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            Director Director = new Director();
            DataClass.TB_Movies dbmovie = new DataClass.TB_Movies();
            Director.director = new List<List_Director>();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                Director.director = db.TB_Directors.Select(d => new List_Director { ID_Directer = d.ID_Director, Name = d.Name_Lastname_Director, Detail = d.Detail_Director }).ToList();
                return View(Director.director);
            }
        }
        public ActionResult Add()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }

            return View();
            
        }
        public ActionResult Edit(string id)
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Edit.Input_director();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                var director = db.TB_Directors.Where(m => m.ID_Director == id).FirstOrDefault();
                model.id_director = director.ID_Director;
                model.Name = director.Name_Lastname_Director;
                model.Detail = director.Detail_Director;
                string url = WebConfigurationManager.AppSettings["Path_img"];
                model.PictureUrl = url + director.Picture_Director;
                if (director.Brithday_Director != null)
                {
                    model.BrithDay =  GetValue.DateToString(director.Brithday_Director.Value);
                }
                ViewBag.name_img = director.Picture_Director;

            }
            return View(model);
            
        }
    }
}

Web_backend/Controllers/UpdateController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_backend.Models;

namespace Web_backend.Controllers
{
    public class UpdateController : Controller
    {
        private string APIURL = string.Empty;
        // GET: Update
        public ActionResult Movie(Edit.Input_movie input, HttpPostedFileBase file)
        {
            var guid = Session["Guid"] as string;
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                input.img = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }
            input.ID_User = new Guid(guid);
            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/Movie", input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index","Movie");
        }
        public ActionResult Caster(Edit.Input_Caster Input, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.PictureUrl = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }


            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/Caster", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Caster");
        }
        public ActionResult Director(Edit.Input_director Input, HttpPostedFileBase file)
        {
            if (file != null)
            {
                var returnedClass = new Helper.Upload();
                Input.PictureUrl = returnedClass.Image(file, Server.MapPath(ConfigurationManager.AppSettings["Path"]));
            }


            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/Director", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Director");
        }
        public ActionResult Genre(Edit.Input_Genre Input)
        {

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/Genre", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Genre");
        }
        public ActionResult Studio(Edit.Input_Studio Input)
        {

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/Studio", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Studio");
        }
        public ActionResult News(Edit.Input_News Input)
        {

            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/News", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "News");
        }
        public ActionResult User(Edit.Input_User Input)
        {
            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL +"/Register/Edit", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Users");
        }
        public ActionResult Status(Edit.Input_Status Input)
        {
            Models.output output = new Models.output();
            APIURL = ConfigurationManager.AppSettings["APIURL"];
            Helper.Request api = new Helper.Request();
            var result = api.send(APIURL + "/Edit/Status_Movie", Input);
            output = Newtonsoft.Json.JsonConvert.DeserializeObject<output>(result);
            return RedirectToAction("Index", "Home");
        }
}
}

Web_backend/Views/Director/Add.cshtml
@{
    ViewBag.Title = "ADD Director";
    @model Web_backend.Models.Add.Input_director

}
@using (Html.BeginForm("Director", "Add", FormMethod.Post, new
{ enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <form class="container">
        <div class="col-md-9">
            <label class="control-label col-md-2">Name:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "name", required = "required" })

                </div>

            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">BrithDay:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextBoxFor(model => model.BrithDay, new { @class = "form-control", @id = "datetimepicker", required = "required" })

                </div>

            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">Detail:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextAreaFor(model => model.Detail, new { @class = "form-control", @id = "Detail", required = "required" })
                </div>


            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">IMG:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <span class="btn btn-default btn-file">
                                Browse… <input name="file" id="file" type="file" />
                            </span>
                        </span>
                        <input type="text" class="form-control" readonly>
                    </div>
                    <img id='img-upload' />
                </div>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-1">
            <button class="btn btn-lg btn-primary btn-block" type="submit">ADD</button>
            </div>
</form>
}
<script>
    $(document).ready(function () {
        $(document).on('change', '.btn-file :file', function () {
            var input = $(this),
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            input.trigger('fileselect', [label]);
        });

        $('.btn-file :file').on('fileselect', function (event, label) {

            var input = $(this).parents('.input-group').find(':text'),
                log = label;

            if (input.length) {
                input.val(log);
            } else {
                if (log) alert(log);
            }

        });
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img-upload').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });
    });
    $("#datetimepicker").datetimepicker({
        format: "MM - DD - YYYY"
    });
</script>   

Web_backend/Views/Director/Edit.cshtml
@{
    ViewBag.Title = "Update Director";
    @model Web_backend.Models.Edit.Input_director
}
@using (Html.BeginForm("Director", "Update", FormMethod.Post, new
{ enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <form class="container">
        <div class="col-md-9">
            <label class="control-label col-md-2">ID_Director:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextBoxFor(model => model.id_director, new { @class = "form-control", @id = "name", @readonly = "readonly" })

                </div>

            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">Name:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "name", required = "required" })

                </div>

            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">BrithDay:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextBoxFor(model => model.BrithDay, new { @class = "form-control", @id = "datetimepicker", required = "required" })

                </div>

            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">Detail:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    @Html.TextAreaFor(model => model.Detail, new { @class = "form-control", @id = "Detail", required = "required" })
                </div>


            </div>
        </div>
        <div class="col-md-9">
            <label class="control-label col-md-2">IMG:</label>
            <div class="col-md-9">
                <div class="form-group col-md-6">
                    <div class="input-group">
                        <span class="input-group-btn">
                            <span class="btn btn-default btn-file">
                                Browse… <input name="file" id="file" value="@ViewBag.name_img" type="file" />
                            </span>
                        </span>
                        <input type="text" class="form-control" value="@ViewBag.name_img" readonly>
                    </div>
                    <img id='img-upload' src="@Model.PictureUrl" />
                </div>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-1">
            <button class="btn btn-lg btn-primary btn-block" type="submit">ADD</button>
            </div>
</form>
}
<script>
    $(document).ready(function () {
        $(document).on('change', '.btn-file :file', function () {
            var input = $(this),
                label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            input.trigger('fileselect', [label]);
        });

        $('.btn-file :file').on('fileselect', function (event, label) {

            var input = $(this).parents('.input-group').find(':text'),
                log = label;

            if (input.length) {
                input.val(log);
            } else {
                if (log) alert(log);
            }

        });
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img-upload').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#file").change(function () {
            readURL(this);
        });
    });

    $("#datetimepicker").datetimepicker({
        format: "MM - DD - YYYY"
    });
</script>

Web_backend/Views/Director/Index.cshtml
@model IEnumerable<Web_backend.Models.List_Director>
@{
    ViewBag.Title = "Director";
}
<div class="">
    <div class="form-group col-md-12">
        <a href="@Url.Action("Add", "Director")" class="btn btn-primary btn-lg"><i class="glyphicon glyphicon-plus"></i> ADD</a>
    </div>
    <table id="myTable" class="table table-bordered">
        <thead>
            <tr>
                <th scope="col" class="col-md-1">ID</th>
                <th scope="col" class="col-md-3">Name</th>
                <th scope="col" class="col-md-3">Detail</th>
                <th scope="col" class="col-md-1">Edit</th>
                <th scope="col" class="col-md-1">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <th scope="row" id="ID_m">@p.ID_Directer</th>
                    <td>@p.Name</td>
                    <td>@p.Detail</td>
                    <td align="center"><a href="@Url.Action("Edit", "Director", new { id = p.ID_Directer })" class="btn btn-warning">Edit</a></td>
                    <td align="center"><a href="@Url.Action("Director", "Delete", new { ID_Director = p.ID_Directer })" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</a></td>
                </tr>
            }

        </tbody>
    </table>
</div>
<script type="text/javascript">
 
</script>