Web_backend/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_backend.Models;
using static Web_backend.Models.Show;

namespace Web_backend.Controllers
{
    public class GenreController : Controller
    {
        // GET: Genre
        public ActionResult Index()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            Genre genre = new Genre();
            DataClass.TB_Movies dbmovie = new DataClass.TB_Movies();
            genre.genre = new List<List_Genre>();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                genre.genre = db.TB_Genres.Select(d => new List_Genre { ID = d.ID_Genre, Name = d.Name_Genre }).ToList();
                return View(genre.genre);
            }

        }
        public ActionResult Add()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            return View();
        }
        public ActionResult Edit(string id)
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Edit.Input_Genre();
            Edit_Movie movie = new Edit_Movie();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                var Edit = db.TB_Genres.Where(m => m.ID_Genre == id).FirstOrDefault();
                if (Edit != null)
                {
                    model.ID = Edit.ID_Genre;
                    model.Name = Edit.Name_Genre;
                }
                return View(model);
            }
        }
    }
}

Web_backend/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Web_backend.Models;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using Web_backend.Helper;
using System.Web.Configuration;

namespace Web_backend.Controllers
{
    public class MovieController : Controller
    {
        private string APIURL = string.Empty;
        // GET: Movie
        public ActionResult Index()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            Movie movie = new Movie();
            DataClass.TB_Movies dbmovie = new DataClass.TB_Movies();
            movie.movie = new List<List_Movie>();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())

            {
                var result = (from c in db.TB_Movies select c);

                foreach (var item in result.AsParallel())
                {
                    movie.movie.Add(new List_Movie
                    {
                        ID_Movie = item.ID_Movie,
                        date = item.Date_Movie.Value.ToString(),
                        Name = item.Name_Movie,
                        status = item.show.Value

                    });
                }
            }
            return View(movie.movie);
        }
        public ActionResult Edit(string id)
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Edit.Input_movie();
            add_DD();
            Edit_Movie movie = new Edit_Movie();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                try
                {
                    var Edit = db.TB_Movies.Where(m => m.ID_Movie == id).FirstOrDefault();
                    if (Edit != null)
                    {

                        model.ID_Movie = Edit.ID_Movie;
                        model.Name_Movie = Edit.Name_Movie;
                        model.Name_Eng = Edit.Name_Movie_eng;
                        model.urlTri = Edit.Trialer;
                        if (Edit.Date_Movie.HasValue)
                        {
                            model.Date_Movie = GetValue.DateToString(Edit.Date_Movie);
                        }
                        model.Detail = Edit.Detail_Movie;
                        model.Rate = Edit.ID_Rate;
                        string url = WebConfigurationManager.AppSettings["Path_img"];
                        model.studio = Edit.ID_Studio;
                        model.img = url + Edit.Picture_Movie;
                        ViewBag.name_img = Edit.Picture_Movie;
                    }
                    var Caster_Movie = db.TB_Cast_Movies.Where(c => c.ID_Movie == id);
                    if (Caster_Movie != null)
                    {
                        foreach (var item in Caster_Movie)
                        {
                            model.Caster.Add(new Models.Edit.List_Cs_Mo
                            {
                                id_Cs = item.ID_Caster,
                                status = item.ID_Status_Caster.Value

                            });
                        }
                    }

                    var Director_Movie = db.TB_Director_Movies.Where(c => c.ID_Movie == id);
                    if (Director_Movie != null)
                    {
                        foreach (var item in Director_Movie)
                        {
                            model.Director.Add(new Models.Edit.List_Dt_Mo
                            {
                                id_Dt = item.ID_Director,
                                status = item.ID_Status_Director.Value

                            });
                        }
                    }

                    var Genre_Movie = db.TB_Genre_Movies.Where(c => c.ID_Movie == id);
                    if (Genre_Movie != null)
                    {
                        foreach (var item in Genre_Movie)
                        {
                            model.Genre.Add(new Models.Edit.List_Ge_Mo
                            {
                                id_Ge = item.ID_Genre

                            });
                        }
                    }


                }
                catch (Exception ex)
                {

                }


                return View(model);
            }
        }
        public ActionResult Delete(string id)
        {
            

            return View();
        }
        public ActionResult Add()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Add.Input_movie();

           // model.ID_User = new Guid(Session["Guid"] as string);
            add_DD();
            return View(model);
        }
        public ActionResult Add_M()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Add.Input_movie();

            // model.ID_User = new Guid(Session["Guid"] as string);
            add_DD();
            return View(model);
        }
        public ActionResult Edit_M(string id)
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Edit.Input_movie();
            add_DD();
            Edit_Movie movie = new Edit_Movie();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                try
                {
                    var Edit = db.TB_Movies.Where(m => m.ID_Movie == id).FirstOrDefault();
                    if (Edit != null)
                    {

                        model.ID_Movie = Edit.ID_Movie;
                        model.Name_Movie = Edit.Name_Movie;
                        model.urlTri = Edit.Trialer;
                        if (Edit.Date_Movie.HasValue)
                        {
                            model.Date_Movie = GetValue.DateToString(Edit.Date_Movie);
                        }
                        model.Detail = Edit.Detail_Movie;
                        model.Rate = Edit.ID_Rate;
                        model.studio = Edit.ID_Studio;
                        string url = WebConfigurationManager.AppSettings["Path_img"];
                        model.img = url+Edit.Picture_Movie;
                    }
                    var Caster_Movie = db.TB_Cast_Movies.Where(c => c.ID_Movie == id);
                    if (Caster_Movie != null)
                    {
                        foreach (var item in Caster_Movie)
                        {
                            model.Caster.Add(new Models.Edit.List_Cs_Mo
                            {
                                id_Cs = item.ID_Caster,
                                status = item.ID_Status_Caster.Value

                            });
                        }
                    }

                    var Director_Movie = db.TB_Director_Movies.Where(c => c.ID_Movie == id);
                    if (Director_Movie != null)
                    {
                        foreach (var item in Director_Movie)
                        {
                            model.Director.Add(new Models.Edit.List_Dt_Mo
                            {
                                id_Dt = item.ID_Director,
                                status = item.ID_Status_Director.Value

                            });
                        }
                    }

                    var Genre_Movie = db.TB_Genre_Movies.Where(c => c.ID_Movie == id);
                    if (Genre_Movie != null)
                    {
                        foreach (var item in Genre_Movie)
                        {
                            model.Genre.Add(new Models.Edit.List_Ge_Mo
                            {
                                id_Ge = item.ID_Genre

                            });
                        }
                    }


                }
                catch (Exception ex)
                {

                }


                return View(model);
            }
        }

        public ActionResult Detail(string id)
        {
            if (Request.Cookies["User"] == null || Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Edit.Input_movie();
            add_DD();
            Edit_Movie movie = new Edit_Movie();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                try
                {
                    var Edit = db.TB_Movies.Where(m => m.ID_Movie == id).FirstOrDefault();
                    if (Edit != null)
                    {

                        model.ID_Movie = Edit.ID_Movie;
                        model.Name_Movie = Edit.Name_Movie;
                        model.urlTri = Edit.Trialer;
                        if (Edit.Date_Movie.HasValue)
                        {
                            model.Date_Movie = GetValue.DateToString(Edit.Date_Movie);
                        }
                        model.Detail = Edit.Detail_Movie;
                        model.Rate = Edit.ID_Rate;
                        model.studio = Edit.ID_Studio;

Web_backend/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_backend.Models;
using static Web_backend.Models.Show;

namespace Web_backend.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            News news = new News();

            news.news = new List<List_News>();
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                news.news = db.TB_News.Select(d => new List_News { ID = d.ID_News.ToString(), Name = d.Name_News }).ToList();
                return View(news.news);
            }
            
        }
        public ActionResult Add()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            News news = new News();

                return View(news.news);
            

        }
        public ActionResult Edit(int id)
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }

            var model = new Edit.Input_News();
            
            using (DataClass.MovieDataContext db = new DataClass.MovieDataContext())
            {
                var Edit = db.TB_News.Where(m => m.ID_News == id).FirstOrDefault();
                if (Edit != null)
                {
                    model.ID = Edit.ID_News.ToString();
                    model.Name = Edit.Name_News;
                    model.Url = Edit.Link_News;
                }
                return View(model);
            }

        }
    }
}

Web_backend/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web_backend.Models;

namespace Web_backend.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index()
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            Users.output user = new Users.output();
            DataClass.TB_Movies dbmovie = new DataClass.TB_Movies();
            user.user = new List<List_User>();
            using (DataClass.UsersDataContext db = new DataClass.UsersDataContext())
            {
                var result = (from u in db.TB_Users join t in db.TB_Type_Users on u.ID_Type equals t.ID_Type select new { u, t });

                foreach (var item in result.AsParallel())
                {
                    user.user.Add(new List_User
                    {
                        Guid_User = item.u.Guid_Users,
                        Email = item.u.Email,
                        Name = item.u.Name_Lastname_Users,
                        type = item.t.Name_Type
                    });
                }
            }
            return View(user.user);
        }
        public ActionResult Edit(string id)
        {
            if (Session["Guid"] == null)
            {
                Response.Cookies["User"].Expires = DateTime.Now.AddDays(-1);
                return RedirectToAction("Index", "Login");
            }
            var model = new Edit.Input_User();
            add_DD();
            using (DataClass.UsersDataContext db = new DataClass.UsersDataContext())
            {
                var Edit = db.TB_Users.Where(m => m.Guid_Users.ToString() == id).FirstOrDefault();
                if (Edit != null)
                {
                    model.guid = Edit.Guid_Users;
                    model.Email = Edit.Email;
                    model.Name = Edit.Name_Lastname_Users;
                    model.Password = Edit.Password;
                    model.mtype = Edit.ID_Type;
                }
                return View(model);
            }
        }
        private void add_DD()
        {
            
           
            using (DataClass.UsersDataContext db = new DataClass.UsersDataContext())
            {
                Edit_User user = new Edit_User();
                user.Type = new List<list_DD>();
                var Type = (from c in db.TB_Type_Users select c);
                foreach (var item in Type.AsParallel())
                {
                    user.Type.Add(new list_DD
                    {
                        id = item.ID_Type,
                        Name = item.Name_Type
                    });
                }
                ViewBag.Type = user.Type;
            }
        }
    }
}

Web_backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/btn-file.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>*@
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
    
    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    <!-- Latest compiled and minified JavaScript -->

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.js"></script>


    <link href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

</head>
<body onload="document.refresh();">
    <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-toggle"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">POPCORN</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                            <i class="glyphicon glyphicon-user"></i> Admin <span class="caret"></span>
                        </a>
                        <ul id="g-account-menu" class="dropdown-menu" role="menu">
                          
                            <li><a href="@Url.Action("Logout", "Home")"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- /container -->
    </div>
    <!-- /Header -->
    <!-- Main -->
    <div class="container">

        <!-- upper section -->
        <div class="row">
            <div class="col-sm-3" id="menu">
                <!-- left -->
            <label class="h3">
                <i class="glyphicon glyphicon-th-list"></i> Menu
            </label>
                
                <hr>

                <ul class="nav nav-stacked">
                    <li><a href="@Url.Action("Index", "Home")" target="ext"><h4><i class="glyphicon glyphicon-home"></i> Home</h4></a></li>
                    <li><a href="@Url.Action("Index", "Movie")" target="ext"><h4><i class="glyphicon glyphicon-film"></i> Movie</h4></a></li>
                    <li><a href="@Url.Action("Index", "Caster")" target="ext"><h4><i class="glyphicon glyphicon-star"></i> Caster</h4></a></li>
                    <li><a href="@Url.Action("Index", "Director")" target="ext"><h4><i class="glyphicon glyphicon-bullhorn"></i> Director</h4></a></li>
                    <li><a href="@Url.Action("Index", "Genre")" target="ext"><h4><i class="glyphicon glyphicon-pushpin"></i> Genre</h4></a></li>
                    <li><a href="@Url.Action("Index", "Studio")" target="ext"><h4><i class="glyphicon glyphicon-facetime-video"></i> Studio</h4></a></li>
                    <li><a href="@Url.Action("Index", "News")" target="ext"><h4><i class="glyphicon glyphicon-list-alt"></i> News </h4></a></li>
                    <li><a href="@Url.Action("Index", "Comment")" target="ext"><h4><i class="glyphicon glyphicon-comment"></i> Comment </h4></a></li>
                    <li><a href="@Url.Action("Index", "Users")" target="ext"><h4><i class="glyphicon glyphicon-user"></i> Users </h4></a></li>
                    
                </ul>

                <hr>

            </div><!-- /span-3 -->
            <div class="col-sm-9">

               <div class="form-inline">
                   <label class="h3">
                       <i class="glyphicon glyphicon-home"></i> @ViewBag.Title
                       </label>
                   

                <hr>
               </div>
                <div class="row">
                    <div class="body-content">
                        @RenderBody()
                    </div>

                    </div><!--/col-->
                </div>
            </div>

            </div>
        <footer class="footer">
            <div class="footer-copyright py-3 text-center">
                © 2018 Copyright:
                <a> Popcron </a>
            </div>

        </footer>
</body>



</html>
<script>

    function mysearch() {
        var input, filter, table, tr, td, i;
        input = document.getElementById("Input_search");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
    $(document).ready(function () {
        var trigger = $('.hamburger'),
            overlay = $('.overlay'),
            isClosed = false;

        trigger.click(function () {
            hamburger_cross();
        });

        function hamburger_cross() {

            if (isClosed == true) {
                overlay.hide();
                trigger.removeClass('is-open');
                trigger.addClass('is-closed');
                isClosed = false;
            } else {
                overlay.show();
                trigger.removeClass('is-closed');
                trigger.addClass('is-open');
                isClosed = true;
            }
        }

        $('[data-toggle="offcanvas"]').click(function () {
            $('#wrapper').toggleClass('toggled');
        });
    });
    function w3_open() {
        document.getElementById("main").style.marginLeft = "20%";
        document.getElementById("mySidebar").style.width = "20%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("openNav").style.display = 'none';
    }
    function w3_close() {
        document.getElementById("main").style.marginLeft = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("openNav").style.display = "inline-block";
    }
    $(document).ready(function () {
        $('#myTable').DataTable();
    });
  
</script>
<style>
    
</style>